#!/bin/bash

# 2017 (c) J. Bouzas
#
# Tests a binary tree implementation
# Executed tests are:
#
#  0 simple insertion
#  1 multiple insertion
#  2 simple removal
#  3 removal of root subs left
#  4 removal of root subs right
#  5 removal of left leaf node
#  6 removal of right leaf node
#  7 removal of root with left leaf
#  8 removal of root with left non-leaf
#  9 removals with miscellaneous depths
#

COMMAND="java -classpath .. abb.AbbProgram"

TESTS=(	'i 0'\
	'i 0 0 1 0 1 1'\
	'i 0 e 0'\
	'i 6 3 e 6'\
	'i 4 8 e 4'\
	'i 5 4 e 4'\
	'i 1 2 e 2'\
	'i 2 1 3 e 2'\
	'i 2 0 1 e 2'\
	'i 3 5 1 7 4 0 2 e 3 5 1')
ANSWERS=('(0)'\
	'(0 () (1))'\
	'()'\
	'(3)'\
	'(8)'\
	'(5)'\
	'(1)'\
	'(1 () (3))'\
	'(1 () (0))'\
	'(2 (0) (4 () (7)))')

for t in "${!TESTS[@]}"
do
	:
	output="$($COMMAND ${TESTS[$t]})"
	ret="$?"
	if [ "$ret" -eq 0 ]
	then
		if [ "$output" == "${ANSWERS[$t]}" ]
		then
			echo "Test $t: ${TESTS[$t]} passed."
			echo "Answer was $output."
		else
			echo "Test $t: ${TESTS[$t]} failed."
			echo "Answer was $output"
			echo "Expected answer was ${ANSWERS[$t]}."
		fi
	else
		echo "Test $t: ${TESTS[$t]} returned error."
		exit
	fi
done
